export type Nutrition = {
  calories: number
  protein: number
  carbs: number
  fat: number
}

export type Recipe = {
  id: string
  title: string
  cuisine: string
  difficulty: "easy" | "medium" | "hard"
  totalMinutes: number
  servings: number
  dietary: Array<"vegan" | "vegetarian" | "gluten-free" | "dairy-free" | "nut-free">
  ingredients: { text: string }[]
  steps: string[]
  nutrition: Nutrition
}

export const cuisines = [
  "Italian",
  "Mexican",
  "Indian",
  "American",
  "Chinese",
  "Japanese",
  "Mediterranean",
  "Middle Eastern",
  "Thai",
  "French",
  "Spanish",
  "Korean",
]

// Note: amounts are for default servings; we scale amounts in UI.
export const allRecipes: Recipe[] = [
  {
    id: "spaghetti-aglio-e-olio",
    title: "Spaghetti Aglio e Olio",
    cuisine: "Italian",
    difficulty: "easy",
    totalMinutes: 20,
    servings: 2,
    dietary: ["vegetarian", "nut-free"],
    ingredients: [
      { text: "200 g spaghetti" },
      { text: "2 tbsp olive oil" },
      { text: "3 cloves garlic, thinly sliced" },
      { text: "1/4 tsp red pepper flakes" },
      { text: "salt and black pepper" },
      { text: "2 tbsp parsley, chopped" },
    ],
    steps: [
      "Cook spaghetti in salted boiling water until al dente.",
      "Warm olive oil and gently toast garlic and pepper flakes.",
      "Toss pasta with garlic oil, add parsley, season to taste.",
      "Serve immediately.",
    ],
    nutrition: { calories: 520, protein: 14, carbs: 75, fat: 18 },
  },
  {
    id: "chickpea-curry",
    title: "Weeknight Chickpea Curry",
    cuisine: "Indian",
    difficulty: "easy",
    totalMinutes: 30,
    servings: 2,
    dietary: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    ingredients: [
      { text: "1 tbsp oil" },
      { text: "1 onion, diced" },
      { text: "2 cloves garlic, minced" },
      { text: "1 tbsp curry powder" },
      { text: "1 can chickpeas, drained" },
      { text: "1 can diced tomatoes" },
      { text: "1/2 cup coconut milk" },
      { text: "salt and pepper" },
    ],
    steps: [
      "Sauté onion and garlic in oil.",
      "Stir in curry powder until fragrant.",
      "Add chickpeas, tomatoes, and coconut milk; simmer 10 minutes.",
      "Season and serve with rice.",
    ],
    nutrition: { calories: 430, protein: 16, carbs: 58, fat: 14 },
  },
  {
    id: "chicken-fajitas",
    title: "Chicken Fajitas",
    cuisine: "Mexican",
    difficulty: "medium",
    totalMinutes: 35,
    servings: 2,
    dietary: ["gluten-free", "dairy-free", "nut-free"],
    ingredients: [
      { text: "2 chicken breasts, sliced" },
      { text: "1 red bell pepper, sliced" },
      { text: "1 onion, sliced" },
      { text: "1 tbsp fajita seasoning" },
      { text: "1 tbsp oil" },
      { text: "salt and pepper" },
      { text: "corn tortillas" },
    ],
    steps: [
      "Cook chicken in oil with seasoning.",
      "Add peppers and onion; sauté until tender-crisp.",
      "Warm tortillas and serve.",
    ],
    nutrition: { calories: 520, protein: 42, carbs: 48, fat: 18 },
  },
  {
    id: "caprese-salad",
    title: "Caprese Salad",
    cuisine: "Italian",
    difficulty: "easy",
    totalMinutes: 10,
    servings: 2,
    dietary: ["vegetarian", "gluten-free", "nut-free"],
    ingredients: [
      { text: "2 tomatoes, sliced" },
      { text: "125 g mozzarella, sliced" },
      { text: "fresh basil leaves" },
      { text: "1 tbsp olive oil" },
      { text: "salt and black pepper" },
    ],
    steps: ["Layer tomato and mozzarella; scatter basil.", "Drizzle with oil, season to taste."],
    nutrition: { calories: 300, protein: 16, carbs: 10, fat: 20 },
  },
  {
    id: "veggie-fried-rice",
    title: "Veggie Fried Rice",
    cuisine: "Chinese",
    difficulty: "easy",
    totalMinutes: 25,
    servings: 2,
    dietary: ["vegetarian", "nut-free"],
    ingredients: [
      { text: "2 cups cooked rice" },
      { text: "1 cup mixed vegetables" },
      { text: "2 eggs, beaten" },
      { text: "1 tbsp soy sauce" },
      { text: "1 tbsp oil" },
      { text: "salt and pepper" },
    ],
    steps: [
      "Scramble eggs and set aside.",
      "Stir-fry vegetables; add rice and soy sauce.",
      "Stir in eggs; season to taste.",
    ],
    nutrition: { calories: 520, protein: 17, carbs: 78, fat: 16 },
  },
  {
    id: "beef-stir-fry",
    title: "Beef Stir-Fry",
    cuisine: "Chinese",
    difficulty: "medium",
    totalMinutes: 30,
    servings: 2,
    dietary: ["dairy-free", "nut-free"],
    ingredients: [
      { text: "250 g beef strips" },
      { text: "1 cup broccoli florets" },
      { text: "1 carrot, sliced" },
      { text: "2 tbsp stir-fry sauce" },
      { text: "1 tbsp oil" },
      { text: "rice to serve" },
    ],
    steps: ["Sear beef; set aside.", "Stir-fry vegetables; add sauce and beef.", "Serve with rice."],
    nutrition: { calories: 560, protein: 36, carbs: 55, fat: 20 },
  },
  {
    id: "greek-salad",
    title: "Greek Salad",
    cuisine: "Mediterranean",
    difficulty: "easy",
    totalMinutes: 15,
    servings: 2,
    dietary: ["vegetarian", "gluten-free", "nut-free"],
    ingredients: [
      { text: "cucumber, chopped" },
      { text: "tomatoes, chopped" },
      { text: "red onion, thinly sliced" },
      { text: "olives" },
      { text: "feta cheese" },
      { text: "olive oil" },
      { text: "oregano, salt, pepper" },
    ],
    steps: ["Combine vegetables and olives.", "Add feta and dress with oil and oregano."],
    nutrition: { calories: 320, protein: 9, carbs: 18, fat: 24 },
  },
  {
    id: "margherita-pizza",
    title: "Quick Margherita Pizza",
    cuisine: "Italian",
    difficulty: "medium",
    totalMinutes: 30,
    servings: 2,
    dietary: ["vegetarian", "nut-free"],
    ingredients: [
      { text: "pizza dough" },
      { text: "tomato sauce" },
      { text: "mozzarella" },
      { text: "fresh basil" },
      { text: "olive oil" },
      { text: "salt and pepper" },
    ],
    steps: ["Stretch dough; top with sauce and mozzarella.", "Bake at high heat; finish with basil and oil."],
    nutrition: { calories: 600, protein: 24, carbs: 80, fat: 20 },
  },
  {
    id: "lentil-soup",
    title: "Hearty Lentil Soup",
    cuisine: "Middle Eastern",
    difficulty: "easy",
    totalMinutes: 40,
    servings: 4,
    dietary: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    ingredients: [
      { text: "1 cup lentils, rinsed" },
      { text: "1 onion, chopped" },
      { text: "2 carrots, chopped" },
      { text: "2 stalks celery, chopped" },
      { text: "1 tsp cumin" },
      { text: "1.2 L vegetable broth" },
      { text: "salt and pepper" },
    ],
    steps: ["Sauté aromatics; add lentils, cumin, and broth.", "Simmer until tender; season to taste."],
    nutrition: { calories: 280, protein: 18, carbs: 45, fat: 3 },
  },
  {
    id: "avocado-toast",
    title: "Avocado Toast with Egg",
    cuisine: "American",
    difficulty: "easy",
    totalMinutes: 10,
    servings: 1,
    dietary: ["vegetarian", "nut-free"],
    ingredients: [
      { text: "1 slice bread" },
      { text: "1/2 avocado" },
      { text: "1 egg" },
      { text: "salt, pepper, chili flakes" },
    ],
    steps: ["Toast bread; mash avocado on top.", "Cook egg and place on toast; season."],
    nutrition: { calories: 350, protein: 14, carbs: 28, fat: 20 },
  },
  {
    id: "tofu-stir-fry",
    title: "Tofu Vegetable Stir-Fry",
    cuisine: "Thai",
    difficulty: "medium",
    totalMinutes: 30,
    servings: 2,
    dietary: ["vegan", "dairy-free", "nut-free"],
    ingredients: [
      { text: "200 g firm tofu, cubed" },
      { text: "1 cup mixed vegetables" },
      { text: "1 tbsp soy sauce" },
      { text: "1 tbsp oil" },
      { text: "garlic and ginger" },
    ],
    steps: ["Brown tofu; set aside.", "Stir-fry vegetables with aromatics; add soy and tofu."],
    nutrition: { calories: 420, protein: 22, carbs: 35, fat: 20 },
  },
  {
    id: "omelette",
    title: "Cheese Omelette",
    cuisine: "French",
    difficulty: "easy",
    totalMinutes: 10,
    servings: 1,
    dietary: ["vegetarian", "gluten-free", "nut-free"],
    ingredients: [{ text: "2 eggs" }, { text: "30 g cheddar" }, { text: "1 tsp butter" }, { text: "salt and pepper" }],
    steps: ["Beat eggs; cook in butter; add cheese and fold."],
    nutrition: { calories: 300, protein: 20, carbs: 2, fat: 24 },
  },
  {
    id: "sushi-bowl",
    title: "Deconstructed Sushi Bowl",
    cuisine: "Japanese",
    difficulty: "medium",
    totalMinutes: 35,
    servings: 2,
    dietary: ["dairy-free", "nut-free"],
    ingredients: [
      { text: "cooked sushi rice" },
      { text: "cucumber, sliced" },
      { text: "avocado, sliced" },
      { text: "nori strips" },
      { text: "soy sauce" },
      { text: "optional: salmon or tofu" },
    ],
    steps: ["Arrange rice with toppings; serve with soy."],
    nutrition: { calories: 540, protein: 20, carbs: 80, fat: 16 },
  },
  {
    id: "taco-salad",
    title: "Taco Salad",
    cuisine: "Mexican",
    difficulty: "easy",
    totalMinutes: 20,
    servings: 2,
    dietary: ["gluten-free", "nut-free"],
    ingredients: [
      { text: "lettuce" },
      { text: "tomatoes" },
      { text: "black beans" },
      { text: "corn" },
      { text: "cheddar" },
      { text: "taco seasoning" },
      { text: "salsa" },
    ],
    steps: ["Combine all ingredients; season to taste."],
    nutrition: { calories: 480, protein: 22, carbs: 50, fat: 18 },
  },
  {
    id: "shakshuka",
    title: "Shakshuka",
    cuisine: "Middle Eastern",
    difficulty: "medium",
    totalMinutes: 30,
    servings: 2,
    dietary: ["vegetarian", "gluten-free", "nut-free"],
    ingredients: [
      { text: "1 onion, sliced" },
      { text: "1 bell pepper, sliced" },
      { text: "2 cups tomato sauce" },
      { text: "4 eggs" },
      { text: "cumin, paprika, chili flakes" },
      { text: "olive oil, salt, pepper" },
    ],
    steps: ["Sauté vegetables; add spices and tomato sauce.", "Make wells and crack eggs; cover until set."],
    nutrition: { calories: 420, protein: 24, carbs: 28, fat: 22 },
  },
  {
    id: "pancakes",
    title: "Fluffy Pancakes",
    cuisine: "American",
    difficulty: "easy",
    totalMinutes: 20,
    servings: 2,
    dietary: ["vegetarian", "nut-free"],
    ingredients: [
      { text: "1 cup flour" },
      { text: "1 tbsp sugar" },
      { text: "1 tsp baking powder" },
      { text: "1 cup milk" },
      { text: "1 egg" },
      { text: "1 tbsp butter, melted" },
      { text: "pinch salt" },
    ],
    steps: ["Mix dry and wet separately; combine gently.", "Cook batter on griddle; flip once bubbles form."],
    nutrition: { calories: 520, protein: 16, carbs: 78, fat: 14 },
  },
  {
    id: "quinoa-salad",
    title: "Quinoa Veggie Salad",
    cuisine: "Mediterranean",
    difficulty: "easy",
    totalMinutes: 25,
    servings: 2,
    dietary: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    ingredients: [
      { text: "1 cup cooked quinoa" },
      { text: "cherry tomatoes" },
      { text: "cucumber" },
      { text: "parsley" },
      { text: "olive oil and lemon juice" },
      { text: "salt and pepper" },
    ],
    steps: ["Combine all; dress with oil and lemon."],
    nutrition: { calories: 420, protein: 13, carbs: 60, fat: 14 },
  },
  {
    id: "garlic-butter-shrimp",
    title: "Garlic Butter Shrimp",
    cuisine: "Spanish",
    difficulty: "easy",
    totalMinutes: 15,
    servings: 2,
    dietary: ["gluten-free", "nut-free"],
    ingredients: [
      { text: "300 g shrimp, peeled" },
      { text: "2 tbsp butter" },
      { text: "3 cloves garlic, minced" },
      { text: "lemon wedges" },
      { text: "parsley" },
      { text: "salt and pepper" },
    ],
    steps: ["Sauté garlic in butter; add shrimp and cook until pink.", "Finish with lemon and parsley."],
    nutrition: { calories: 400, protein: 36, carbs: 4, fat: 26 },
  },
  {
    id: "burrito-bowl",
    title: "Burrito Bowl",
    cuisine: "Mexican",
    difficulty: "easy",
    totalMinutes: 25,
    servings: 2,
    dietary: ["gluten-free", "nut-free"],
    ingredients: [
      { text: "rice" },
      { text: "black beans" },
      { text: "corn" },
      { text: "salsa" },
      { text: "cheddar" },
      { text: "optional: chicken" },
    ],
    steps: ["Arrange rice with toppings; season to taste."],
    nutrition: { calories: 560, protein: 22, carbs: 84, fat: 16 },
  },
  {
    id: "tomato-soup",
    title: "Creamy Tomato Soup",
    cuisine: "American",
    difficulty: "easy",
    totalMinutes: 25,
    servings: 2,
    dietary: ["vegetarian", "nut-free"],
    ingredients: [
      { text: "1 tbsp butter" },
      { text: "1 onion, chopped" },
      { text: "2 cups crushed tomatoes" },
      { text: "1/2 cup cream or milk" },
      { text: "salt, pepper, basil" },
    ],
    steps: ["Sauté onion in butter; add tomatoes; simmer.", "Blend and add cream; season to taste."],
    nutrition: { calories: 420, protein: 10, carbs: 36, fat: 26 },
  },
  {
    id: "caesar-salad",
    title: "Simple Caesar Salad",
    cuisine: "Italian",
    difficulty: "easy",
    totalMinutes: 15,
    servings: 2,
    dietary: ["nut-free"],
    ingredients: [
      { text: "romaine lettuce" },
      { text: "croutons" },
      { text: "parmesan" },
      { text: "caesar dressing" },
      { text: "optional: chicken" },
    ],
    steps: ["Toss lettuce with dressing, croutons, and parmesan."],
    nutrition: { calories: 420, protein: 18, carbs: 22, fat: 28 },
  },
  {
    id: "banana-smoothie",
    title: "Banana Peanut Smoothie",
    cuisine: "American",
    difficulty: "easy",
    totalMinutes: 5,
    servings: 1,
    dietary: ["gluten-free"],
    ingredients: [{ text: "1 banana" }, { text: "2 tbsp peanut butter" }, { text: "1 cup milk" }, { text: "ice" }],
    steps: ["Blend all until smooth."],
    nutrition: { calories: 420, protein: 16, carbs: 45, fat: 18 },
  },
  {
    id: "miso-soup",
    title: "Miso Soup",
    cuisine: "Japanese",
    difficulty: "easy",
    totalMinutes: 15,
    servings: 2,
    dietary: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    ingredients: [
      { text: "2 cups water" },
      { text: "1 tbsp miso paste" },
      { text: "tofu cubes" },
      { text: "scallions" },
      { text: "wakame (optional)" },
    ],
    steps: ["Warm water; dissolve miso; add tofu and scallions."],
    nutrition: { calories: 150, protein: 10, carbs: 10, fat: 7 },
  },
  {
    id: "couscous-salad",
    title: "Couscous Salad",
    cuisine: "Mediterranean",
    difficulty: "easy",
    totalMinutes: 20,
    servings: 2,
    dietary: ["vegetarian", "nut-free"],
    ingredients: [
      { text: "1 cup couscous" },
      { text: "cherry tomatoes" },
      { text: "cucumber" },
      { text: "olive oil and lemon" },
      { text: "parsley" },
      { text: "salt and pepper" },
    ],
    steps: ["Hydrate couscous; mix with vegetables and dressing."],
    nutrition: { calories: 480, protein: 12, carbs: 78, fat: 12 },
  },
  {
    id: "egg-fried-noodles",
    title: "Egg Fried Noodles",
    cuisine: "Chinese",
    difficulty: "easy",
    totalMinutes: 20,
    servings: 2,
    dietary: ["nut-free"],
    ingredients: [
      { text: "noodles, cooked" },
      { text: "2 eggs" },
      { text: "soy sauce" },
      { text: "mixed veggies" },
      { text: "oil" },
    ],
    steps: ["Scramble eggs; stir-fry noodles and veggies; add soy."],
    nutrition: { calories: 540, protein: 18, carbs: 76, fat: 16 },
  },
  {
    id: "roasted-veggies",
    title: "Roasted Veggies & Quinoa",
    cuisine: "American",
    difficulty: "easy",
    totalMinutes: 35,
    servings: 2,
    dietary: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    ingredients: [
      { text: "assorted vegetables" },
      { text: "olive oil" },
      { text: "quinoa, cooked" },
      { text: "salt, pepper" },
    ],
    steps: ["Roast vegetables; serve over quinoa."],
    nutrition: { calories: 460, protein: 14, carbs: 66, fat: 14 },
  },
  {
    id: "butter-chicken",
    title: "Butter Chicken (quick)",
    cuisine: "Indian",
    difficulty: "medium",
    totalMinutes: 35,
    servings: 2,
    dietary: ["nut-free"],
    ingredients: [
      { text: "2 chicken breasts, cubed" },
      { text: "butter" },
      { text: "tomato puree" },
      { text: "cream" },
      { text: "garam masala" },
      { text: "salt, pepper" },
    ],
    steps: ["Brown chicken; simmer in tomato, butter, cream, and spices."],
    nutrition: { calories: 680, protein: 42, carbs: 20, fat: 46 },
  },
  {
    id: "kimchi-fried-rice",
    title: "Kimchi Fried Rice",
    cuisine: "Korean",
    difficulty: "easy",
    totalMinutes: 20,
    servings: 2,
    dietary: ["nut-free"],
    ingredients: [
      { text: "2 cups cooked rice" },
      { text: "1 cup chopped kimchi" },
      { text: "1 tbsp gochujang" },
      { text: "2 eggs" },
      { text: "oil" },
      { text: "scallions" },
    ],
    steps: ["Stir-fry kimchi and gochujang; add rice.", "Top with fried eggs and scallions."],
    nutrition: { calories: 560, protein: 16, carbs: 82, fat: 16 },
  },
]
